version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    expose:
      - '5432'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    expose:
      - '6379'
    ports:
      - '6379:6379'
