springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api-docs

server:
  servlet:
    session:
      cookie:
        path: /
        name: JSESSIONID
#        domain:
        http-only: true
        secure: false
      timeout: 3600

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/mydatabase
    username: myuser
    password: secret
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
  jpa:
    database: postgresql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  session:
    store-type: redis
    redis:
      namespace: spring:session